name: CI for GUL14

on:
  push

jobs:
  build-and-run-tests-on-ubuntu:
    uses: ./.github/workflows/build-and-run-tests-posix.yml
    with:
      platform: ubuntu-latest

  build-and-run-tests-on-macos:
    uses: ./.github/workflows/build-and-run-tests-posix.yml
    with:
      platform: macos-latest

  build-and-run-tests-on-windows:
    uses: ./.github/workflows/build-and-run-tests-windows.yml
    with:
      platform: windows-latest
