name: Test on Windows

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'include'
      - 'src'
      - 'tests'
      - 'tools'
  workflow_dispatch:

jobs:
  build-and-asan:
    name: Test on Windows
    runs-on: windows-latest

    steps:
      - name: Intro
        run: echo "Branch ${{ github.ref }} on repository ${{ github.repository }}"

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install meson ninja

      - name: Call build and test script
        shell: cmd
        # test ^<buildtype^> ^<platform^> - Run the unit tests for the specified build type and platform
        # ^<buildtype^> is one of "release" or "debug"
        # ^<platform^> is one of "x86" or "x64"
        run: |
          "tools\make_vs.bat" test debug x64

      - name: Prepare MSVC
        if: false
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x64

      - name: Configure build directories
        if: false
        run: |
          meson setup --buildtype=debug build.asan -Db_sanitize=address

      - name: Build and run ASAN tests
        if: false
        run: meson test -C build.asan

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: build-dirs
          path: |
            # build.asan/
            build/x64-windows/debug/
