name: Test on Windows

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'include'
      - 'src'
      - 'tests'
      - 'tools'

jobs:
  build_n_test:
    name: Build and Test on Windows
    runs-on: windows-latest

    steps:
      - name: Fetch repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install meson ninja

      - name: Call build and test
        shell: cmd
        # test ^<buildtype^> ^<platform^> - Run the unit tests for the specified build type and platform
        # ^<buildtype^> is one of "release" or "debug"
        # ^<platform^> is one of "x86" or "x64"
        run: |
          "tools\make_vs.bat" test debug x64
